#!/bin/bash
export PYSPARK_DRIVER_PYTHON=/Anaconda/bin/jupyter
export PYSPARK_DRIVER_PYTHON_OPTS="notebook --NotebookApp.open_browser=False --NotebookApp.ip='*' --NotebookApp.port=8880"
export PYSPARK_PYTHON=/anaconda/bin/python2.7
/usr/local/spark/bin/pyspark --packages com.databricks:spark-csv_2.11:1.2.0
